name: build and deploy
on:
  workflow_dispatch:
    inputs:
      dev:
        description: 'Run dev'
        required: true
        default: 'true'
        type: choice
        options: ['true', 'false']
      stage:
        description: 'Run Stage'
        required: true
        default: 'false'
        type: choice
        options: ['true', 'false']
      prod_dr:
        description: 'Run prod & dr'
        required: true
        default: 'true'
        type: choice
        options: ['true', 'false']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: build repository
        run: echo "executing build"

  artifact:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: "executing artifact"
        run: echo "executing artifact"

  deploy:
    needs: build
    if: ${{ github.event.inputs.dev == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: "executing deploy"
        run: echo "executing deploy"

  deploy-test:
    needs: artifact
    if: ${{ github.event.inputs.stage == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: "executing deploy"
        run: echo "executing deploy"

  deploy-prod:
    needs: artifact
    if: ${{ github.event.inputs.prod_dr == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: "executing deploy"
        run: echo "executing deploy"

  deploy-dr:
    needs: artifact
    if: ${{ github.event.inputs.prod_dr == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: "executing deploy"
        run: echo "executing deploy"
