name: build and deploy
on:
 push:
  branches: ["main"]

jobs:
 build:
  runs-on: ubuthu-latest
  steps:
   - name: checkout repository
     uses: actions/checkout@v4
   - name: executebuild repository
     run: "exucutingbuild"
 deploy:
  runs-on: ubuthu-latest
  steps:
   - name: "exucutingdeploy"
     run: "exucutingdeploy"
